#!/bin/sh /etc/rc.common
# Copyright (C) 2021 ImmortalWrt

USE_PROCD=1
START=99

NAME="naiveproxy"

start_instance() {
	local section="$1"
	local enable listen_addr server_addr extra_argument

	config_get_bool "enable" "$section" "enable" "0"
	[ "$enable" -eq "1" ] || return 0

	config_get "listen_addr" "$section" "listen_addr"
	config_get "server_addr" "$section" "server_addr"
	config_get "extra_argument" "$section" "extra_argument"

	if [ -z "$listen_addr" ] || [ -z "$server_addr" ]; then
		logger -t "$NAME" "Skip instance '$section': listen_addr and server_addr are required"
		return 1
	fi

	procd_open_instance "$section"

	procd_set_param command naive
	procd_append_param command --listen="$listen_addr"
	procd_append_param command --proxy="$server_addr"
	[ -n "$extra_argument" ] && procd_append_param command $extra_argument

	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

start_service() {
	config_load "$NAME"
	config_foreach start_instance naiveproxy
	return 0
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
